language: node_js
node_js:
  - "stable"
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: uncovered-brass.surge.sh
  project: ./build/
on:
  branch: master